# Generated by Django 4.2.9 on 2024-01-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.category'),
        ),
    ]
